### ISSUE TITLE
More disk space to cache CARGO_TARGET_DIR

### ISSUE THREAD

**Issue by geigerzaehler** [oscoin/ci#9]
To speed up builds we would like to cache `CARGO_TARGET_DIR` (which is usually `./target`) between builds of `radicle-registry`. Caching the target directory gives a significant speed up over just ussing `sccache` since only the project code is recompiled. (I’ll try to provide hard numbers later.)

The target directory contains roughly 4GB for `radicle-registry`. So for sensible caching we’ll need roughly 8GB of space on the `/cache` volume. Inside the project we’ll also need to think of a strategy to clean up the target directory.

**Comment by kim** [comment]
> 8GB
👀 

> Caching the target directory gives a significant speed up over just ussing sccache since only the project code is recompiled.

I'm not sure this is entirely sound - it most likely depends on file modification times, which might be skewed due to fresh git checkouts in every step. What you want is probably to cache this only on feature branches, and wipe the cache once before merging. A build bot would be handy to stage uncached builds before master...

**Comment by geigerzaehler** [comment]
> I'm not sure this is entirely sound - it most likely depends on file modification times, which might be skewed due to fresh git checkouts in every step.

I also had these concerns but this worked at least on CircleCI.

> What you want is probably to cache this only on feature branches, and wipe the cache once before merging. A build bot would be handy to stage uncached builds before master...

Yes, this is indeed something we need to address.

**Comment by kim** [comment]
![Screenshot_2019-10-15 oscoin-parity-wasm-prototype · monadic](https://user-images.githubusercontent.com/6163/66820731-87193680-ef41-11e9-8d01-8699b34e806e.png)
